./train-text-from-scratch \
    --vocab-model models/ggml-vocab.bin \
    --ctx 256 \
    --embd 192 \
    --head 8 \
    --layer 4 \
    --checkpoint-out chk-bluey-8x4x192.bin \
    --model-out ggml-bluey-8x4x192-v1.bin \
    --train-data "bluey.txt" \
    -t 4 -b 8 -n 32 --seed 1 \
    --adam-iter 16 \
    --print-details-interval 4 \
    --use-flash \
    --mem-compute 8